Pretty large commit:\n - Server shutdown and restart commands\n - Transformer API for items

diff --git a/src/commonapi/edge-commonapi b/src/commonapi/edge-commonapi
--- a/src/commonapi/edge-commonapi
+++ b/src/commonapi/edge-commonapi
@@ -6,11 +6,19 @@ function start() {
 	
 	java -cp "$libs" org.asf.edge.commonapi.EdgeCommonApiServerMain "$@"
 	code=$?
+	if [ "$code" != "0" ]; then
+		if [ "$code" != "237" ]; then
+			1>&2 echo "Error: server exited with code $code, restarting!"
+		fi
+		start
+		return
+	fi
 	if [ "$code" == "0" ] && [ -f commonapiupdater.jar ]; then
 		java -cp "commonapiupdater.jar" org.asf.edge.commonapi.EdgeCommonApiServerUpdater --update
 		rm commonapiupdater.jar
 		echo
 		start
+		return
 	fi
 	exit $code
 }
diff --git a/src/contentserver/edge-contentserver b/src/contentserver/edge-contentserver
--- a/src/contentserver/edge-contentserver
+++ b/src/contentserver/edge-contentserver
@@ -6,11 +6,19 @@ function start() {
 	
 	java -cp "$libs" org.asf.edge.contentserver.EdgeContentServerMain "$@"
 	code=$?
+	if [ "$code" != "0" ]; then
+		if [ "$code" != "237" ]; then
+			1>&2 echo "Error: server exited with code $code, restarting!"
+		fi
+		start
+		return
+	fi
 	if [ "$code" == "0" ] && [ -f contentserverupdater.jar ]; then
 		java -cp "contentserverupdater.jar" org.asf.edge.contentserver.EdgeContentServerUpdater --update
 		rm contentserverupdater.jar
 		echo
 		start
+		return
 	fi
 	exit $code
 }
diff --git a/src/gameplayapi/edge-gameplayapi b/src/gameplayapi/edge-gameplayapi
--- a/src/gameplayapi/edge-gameplayapi
+++ b/src/gameplayapi/edge-gameplayapi
@@ -6,11 +6,19 @@ function start() {
 	
 	java -cp "$libs" org.asf.edge.gameplayapi.EdgeGameplayApiServerMain "$@"
 	code=$?
+	if [ "$code" != "0" ]; then
+		if [ "$code" != "237" ]; then
+			1>&2 echo "Error: server exited with code $code, restarting!"
+		fi
+		start
+		return
+	fi
 	if [ "$code" == "0" ] && [ -f gameplayapiupdater.jar ]; then
 		java -cp "gameplayapiupdater.jar" org.asf.edge.gameplayapi.EdgeGameplayApiServerUpdater --update
 		rm gameplayapiupdater.jar
 		echo
 		start
+		return
 	fi
 	exit $code
 }
diff --git a/src/globalserver/edge b/src/globalserver/edge
--- a/src/globalserver/edge
+++ b/src/globalserver/edge
@@ -6,11 +6,19 @@ function start() {
 	
 	java -cp "$libs" org.asf.edge.globalserver.EdgeGlobalServerMain "$@"
 	code=$?
+	if [ "$code" != "0" ]; then
+		if [ "$code" != "237" ]; then
+			1>&2 echo "Error: server exited with code $code, restarting!"
+		fi
+		start
+		return
+	fi
 	if [ "$code" == "0" ] && [ -f updater.jar ]; then
 		java -cp "updater.jar" org.asf.edge.globalserver.EdgeGlobalServerUpdater --update
 		rm updater.jar
 		echo
 		start
+		return
 	fi
 	exit $code
 }
